version: '2'
services:
  InfluxDB:
    image: influxdb:1.7-alpine
    ports:
      - "8086:8086"
    volumes:
      - /Users/simon/docker-container/logging/influx:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED: 'true'
      INFLUXDB_DB: 'logging_demo'
      INFLUXDB_HTTP_AUTH_ENABLED: 'false'
      INFLUXDB_ADMIN_USER: influxadmin
      INFLUXDB_ADMIN_PASSWORD: admin12345
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: user12345
    restart: always

  TimeseriesAdmin:
    image: timeseriesadmin/timeseriesadmin:latest
    ports:
      - "8085:80"
    restart: always